 * Serving Flask app 'program'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://cs3103.cs.unb.ca:8037
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 125-789-849
131.202.241.41 - - [31/Mar/2025 13:13:52] "GET /game/search HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:13:52] "GET /session HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:13:52] "GET /session HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:13:54] "[36mPOST /game/addGame HTTP/1.1[0m" 304 -
131.202.241.41 - - [31/Mar/2025 13:15:02] "[36mPOST /game/addGame HTTP/1.1[0m" 304 -
131.202.241.41 - - [31/Mar/2025 13:17:26] "GET /game/search HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:17:26] "GET /session HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:17:26] "GET /session HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:17:38] "[36mPOST /game/addGame HTTP/1.1[0m" 304 -
131.202.241.41 - - [31/Mar/2025 13:17:46] "POST /game/addGame HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:17:48] "[36mPOST /game/addGame HTTP/1.1[0m" 304 -
131.202.241.41 - - [31/Mar/2025 13:18:04] "[36mPOST /game/addGame HTTP/1.1[0m" 304 -
131.202.241.41 - - [31/Mar/2025 13:18:13] "[35m[1mPOST /game/addGame HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home1/ugrads/ivanderp/cs3103/Project/Project/Project/py/program.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/home1/ugrads/ivanderp/cs3103/Project/Project/Project/py/program.py", line 321, in post
    steam_data=response.json()[steamId]['data']
KeyError: 'data'
131.202.241.41 - - [31/Mar/2025 13:18:52] "[35m[1mPOST /game/addGame HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home1/ugrads/ivanderp/.local/lib/python3.9/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home1/ugrads/ivanderp/cs3103/Project/Project/Project/py/program.py", line 37, in wrapper
    return f(*args, **kwargs)
  File "/home1/ugrads/ivanderp/cs3103/Project/Project/Project/py/program.py", line 328, in post
    publisher=steam_data['publishers'][0]
KeyError: 'publishers'
131.202.241.41 - - [31/Mar/2025 13:19:06] "POST /game/addGame HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:19:18] "POST /game/addGame HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:19:27] "POST /game/addGame HTTP/1.1" 200 -
131.202.241.41 - - [31/Mar/2025 13:19:36] "POST /game/addGame HTTP/1.1" 200 -
